POST http://localhost:8080/item
Content-Type: application/json

{
  "name" : "사과",
  "price": 12000,
  "stockQuantity": 5
}

###
GET http://localhost:8080/items

###
GET http://localhost:8080/item/1

###
PUT http://localhost:8080/item/1
Content-Type: application/json

{
  "price" : 10000,
  "stockQuantity": 10
}